#!/bin/sh

# Kvaser Linux Canlib
# Initialize or shutdown a LAPcan PCMCIA CAN device
# Copyright 2002-2005 KVASER AB, Sweden.  All rights reserved.

if [ -r ./shared ] ; then . ./shared ; else . /etc/pcmcia/shared ; fi
get_info $DEVICE

# Load site-specific settings
ADDRESS="$SCHEME,$SOCKET"
#   No options yet
# . $0.opts

case "$ACTION" in

'start')
    rm -f /dev/${DEVICE}
    mknod /dev/${DEVICE} c $MAJOR $MINOR
    ;;
'check')
    fuser -s /dev/${DEVICE} && exit 1
    ;;
'stop')
    fuser -k /dev/${DEVICE} > /dev/null
    rm -f /dev/${DEVICE}
    ;;
'cksum')
    chk_simple "$3,$SOCKET,$INSTANCE" || exit 1
    ;;    
'suspend'|'resume')
    ;;

*)
    usage
    ;;

esac

exit 0
